@hostname = localhost
@port = 8789
@host = {{hostname}}:{{port}}
@api = sales
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@ID = 2


# expert user interface
# ./mvnw clean spring-boot:run
# ./mvnw clean install
# java -jar target/Procurement*

###
#****************************************************
#                   CREATE A STORE
#****************************************************
curl -X POST http://localhost:8789/sales/store \
 -H 'Content-type:application/json' \
 -d '{"address": "fake address", "managerName": "steve"}'

###
#****************************************************
#                CREATE A STORE SALE
#****************************************************
curl -X POST http://localhost:8789/sales/store/33333200 \
 -H 'Content-type:application/json' \
 -d '{
        "productName": "2022 Polygon Siskiu D5 - Dual Suspension Mountain Bike",
        "quantity": 1
    }'

###
#****************************************************
#                   GET ALL STORES
#****************************************************
# curl -v http://localhost:8789/sales/store | json_pp
GET http://localhost:8789/sales/store

###
#****************************************************
#                   GET ONE STORE
#****************************************************
# curl -v http://localhost:8789/sales/store/33333200 | json_pp
GET http://localhost:8789/sales/store/33333200

###
#****************************************************
#               GET ONE STORES SALES
#****************************************************
# curl -v http://localhost:8789/sales/store/33333200/purchases | json_pp
GET http://localhost:8789/sales/store/33333200/purchases

###
#****************************************************
#               GET ALL STORES SALES
#****************************************************
# curl -v http://localhost:8789/sales/store/purchases | json_pp
GET http://localhost:8789/sales/store/purchases

###
#****************************************************
#                 CREATE ONLINE SALE
#****************************************************
curl -X POST http://localhost:8789/sales/online \
 -H 'Content-type:application/json' \
 -d '{
        "customerName": "Bill Murray",
        "address": "13 The Farm, Adelaide, 4321",
        "productName": "2022 Polygon Siskiu D5 - Dual Suspension Mountain Bike",
        "quantity": "1"
    }'

###
#****************************************************
#                GET ALL ONLINE SALES
#****************************************************
# curl -v http://localhost:8789/sales/online | json_pp
GET http://localhost:8789/sales/online HTTP/1.1

###
#****************************************************
#                GET ONE ONLINE SALE
#****************************************************
# curl -v http://localhost:8789/sales/online/9999901 | json_pp
GET http://localhost:8789/sales/online/9999901 HTTP/1.1

###
#****************************************************
#                GET PRODUCT BY SALE
#****************************************************
# curl -v http://localhost:8789/sales/9999900/product | json_pp
GET http://localhost:8789/sales/9999900/product HTTP/1.1
=======
#                GET ALL SALES
#****************************************************
# curl -v http://localhost:8789/sales | json_pp
GET http://localhost:8789/sales HTTP/1.1

###
#****************************************************
#                GET ONE SALE
#****************************************************
# curl -v http://localhost:8789/sales/9999901 | json_pp
GET http://localhost:8789/sales/9999901 HTTP/1.1

###
#****************************************************
#                  UNAVAILABLE
#****************************************************
# curl -v http://localhost:8789/sales/unavailable | json_pp
GET http://localhost:8789/sales/unavailable HTTP/1.1

###
#****************************************************
#                   BACKORDER
#****************************************************
# curl -v http://localhost:8789/sales/backorder/9999901 | json_pp
GET http://localhost:8789/sales/backorder/9999900 HTTP/1.1

###
#****************************************************
#                GET PRODUCT BY SALE
#****************************************************
# curl -v http://localhost:8789/sales/9999900/product | json_pp
GET http://localhost:8789/sales/9999901/product HTTP/1.1
